### ISSUE TITLE
custom accept route

### ISSUE THREAD

**Issue by Jehfkemsy** [UPE-FIU/pear-ShellHacks#17]
@Barnes2197 we need a route that takes a list of haker IDs and accept them

**Comment by Tommy2016x** [comment]
We already have a method that does that. Under the admin/accept route. It accepts an array of ShellIDs and accepts them

**Comment by Jehfkemsy** [comment]
aight...thought it didn't exist since its not on the dashboard

**Comment by Jehfkemsy** [comment]
issues has already been solved, so i'm closing it
